Centralise specification of prefixes and OWL entity dependencies #35
obophenotype/brain_data_standards_ontologies pull request #39
Opened 2021-02-19 11:31 UTC by hkir-dev

context json added, template updated

2021-02-24 16:18 UTC, dosumis requested changes
Small change requested in comment

2021-02-24 16:18 UTC, dosumis commented on src/ontology/template_prefixes.json
> +    "ensembl": "https://identifiers.org/ensembl:"
Chris requested a different ensembl URL:  `http://identifiers.org/ensembl/`

2021-02-25 06:55 UTC, hkir-dev commented on src/ontology/template_prefixes.json
> +    "ensembl": "https://identifiers.org/ensembl:"
URL updated

2021-03-05 11:11 UTC, dosumis approved these changes

2021-03-05 11:11 UTC, merged